### ISSUE TITLE
Using our own dataset

### ISSUE THREAD

**Issue by Kiruko** [vinits5/learning3d#1]
Hi ! 

First thank you very much for this incredible library !

I would like to use your library to do point cloud registration with two pointclouds but I am struggling to see how to do it. Is there any function that I missed ? Thank you in advance for your answer.

**Comment by vinits5** [comment]
Hey @Kiruko,

Thank you for pointing out the need for a class to use your own dataset. I will add this functionality. Any other suggestions are always welcome.

**Comment by BernardoTeixeira** [comment]
Same problem here, it would be awesome to use this on own data but cannot figure out how
Great repo anyhow!

**Comment by vinits5** [comment]
@BernardoTeixeira 
Thank you for your appreciation. Please find this link to use your own data: https://github.com/vinits5/learning3d#use-your-own-data
