### ISSUE TITLE
ModuleNotFoundError when running examples

### ISSUE THREAD

**Issue by h4k1m0u** [vinits5/learning3d#12]
Sorry for the noob question, but how do you run the training/test examples located inside learning3d/examples?
I've installed all the requirements and I'm not using virtualenv, yet this is the error I get:

```
Traceback (most recent call last):
  File "train_pointnet.py", line 20, in <module>
    from learning3d.models import PointNet
ModuleNotFoundError: No module named 'learning3d'
```

I know I can get rid of that error with the following (and editing checkpoints paths I suppose):

```python
# from learning3d.models import PointNet
# from learning3d.models import Classifier
# from learning3d.data_utils import ClassificationData, ModelNet40Data
from models import PointNet
from models import Classifier
from data_utils import ClassificationData, ModelNet40Data
```

But I was curious how you run these examples directly without editing any script (since I can't see any `setup.py` at the root forlder to make this folder a python module)?

**Comment by vinits5** [comment]
Hey, thanks for showing interest in learning3d.
Ideally, you should not run test files inside the learning3d directory The main objective here was to use learning3d as a package and import everything from outside of the directory. Hope this answers your query.
If you want to forcefully run them inside the folder then you will have to update a lot of relative imports in multiple files.

**Comment by vinits5** [comment]
I hope the problem is resolved on your end.
I am closing this issue due to prolonged inactivity. Feel free to open if you have some new findings.

**Comment by 01yaoyuan** [comment]
![image](https://user-images.githubusercontent.com/41202120/230423808-d4d88391-c12f-46fe-a76d-3b8847502fba.png)
Hello,while I run pcrnet in my virtual python envirometn outside learning3d ,I come across this problem.could you help to solve ,sincererly hope

**Comment by luizavolpi** [comment]
Hi! Thank you so much for creating this package!
 
I am having the same problem, "ModuleNotFoundError when running examples", except I am running test_pointconv.py from out of the learning3d directory, as suggested in the README. Would you know what could be happening?

Thank you :)
