### ISSUE TITLE
No module named 'emd'

### ISSUE THREAD

**Issue by TLi347** [vinits5/learning3d#13]
Hi,

When I use EMD loss in losses.py, it showed:

File "/XXX/learning3d/losses/emd.py", line 6, in emd
    from emd import EMDLoss
ModuleNotFoundError: No module named 'emd'

**Comment by pb0316** [comment]
same issue.

**Comment by vinits5** [comment]
Hey everyone,

Thanks for pointing out the problems. EMD and Chamfer Distance (CD) implementations will only work if your device has cuda installed in it. You will have to run python3 setup.py install to compile EMD loss.
There are no great CPU based implementations so I am also looking for a good EMD and CD loss implementations. I will update this repository as soon as I find them.

**Comment by vinits5** [comment]
https://github.com/vinits5/learning3d/blob/master/losses/chamfer_distance.py#L42
Chamfer distance loss function is updated with purely PyTorch based implementation. @pb0316 and @TLi347 can you please try it once? Thank you.
I will also try to look for PyTorch based EMD loss function and will update here.
