### ISSUE TITLE
prepare data to train

### ISSUE THREAD

**Issue by SabraHashemi** [vinits5/learning3d#14]
i want to train a model to register and match 2 point cloud to classify objects , how can I use these repo to train my data?

**Comment by vinits5** [comment]
Hi @SabraHashemi ,
Sorry for the delay in response. There are two possible options.
1. Store the data that you have in h5 files just like ModelNet40. Then, you can easily use this repository by using ModelNet40 dataloader.
2. You can store point clouds in any feasible way for you and re-write the code to read point clouds in data_utils/dataloader.py file.
Hope this helps. Let me know if you still have any question.
