### ISSUE TITLE
ModuleNotFoundError: No module named 'learning3d'

### ISSUE THREAD

**Issue by luizavolpi** [vinits5/learning3d#21]
Hi, thank you so much for your repository. I am facing an issue when trying to use it, and I was hoping someone could shed some light on how to fix it. 
When I try importing it as:

from learning3d.models import create_pointconv

I get a "ModuleNotFoundError: No module named 'learning3d'".

I have the learning3d folder in my directory and although I am trying to run it on my own code, I wasn't able to run it using the test_pointconv.py as suggested in the README file (I copied it out of the examples folder and put it in my directory). 
I've checked the name of the folder, and the name I am using to import, and it seems to be alright. The folder shows up in my terminal when I list it.

I have tried cloning it in a new separate project and the same happened. I am not sure how to proceed, what is it I am missing?

Thank you for your time!

**Comment by vinits5** [comment]
Hey @luizavolpi , I hope you have the following directory structure:
- root_dir
            - learning3d
            - test_pointconv.py
Please check it and let me know if this helps.

**Comment by luizavolpi** [comment]
Hello,Thank you for your response! Yes, I was doing this already, but I’m  still unsuccessful.Thank you,LuizaOn Oct 22, 2023, at 12:50 PM, ViNiT SaRoDe ***@***.***> wrote:﻿
Hey @luizavolpi , I hope you have the following directory structure:

root_dir
- learning3d
- test_pointconv.py
Please check it and let me know if this helps.
