### ISSUE TITLE
Segmentation not implemented

### ISSUE THREAD

**Issue by UltraViolet28** [vinits5/learning3d#22]
Hello, 

I wanted to try out the PointNet for segmentation, but I couldn't find any implementations of it in the examples. It would be great if there could be some additional examples or code snippets showcasing how to use PointNet for segmentation tasks.

**Comment by vinits5** [comment]
First of all sorry for the delayed response.
@UltraViolet28, I will add segmentation pre-trained models of PointNet and some example code snippets to try it out quickly.
It will take maybe a week or two to update the code.

**Comment by elvistheyo** [comment]
@vinits5 where can i find the segmentation pre-trained models of PointNet?
