### ISSUE TITLE
Cannot download ModelNet40 dataset

### ISSUE THREAD

**Issue by barnabe-perspectives** [vinits5/learning3d#23]
Hello @vinits5,

Thank you for this amazing work.
I would love to try out your package but i can't manage to download the ModelNet 40 data used in the examples.
Both your download class ([dataloaders.py](https://github.com/vinits5/learning3d/blob/master/data_utils/dataloaders.py)) and direct download link ([https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip](url)) in a browser are not working, the connection is timing out .

Do you know another link to access the dataset ?

Thanks,
Barnabe

**Comment by vinits5** [comment]
Hey @barnabe-perspectives ,
I think the link still works. Please try the following link from browser:
https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip
(It's working in my web browser. If it fails then do send me you email, I will share the data with you.)

**Comment by conggalam12** [comment]
Hey @vinits5 ,
I can't download this dataset , can you share with me ?.

**Comment by vinits5** [comment]
@conggalam12 please use this link to download the dataset.
https://huggingface.co/datasets/Msun/modelnet40/resolve/main/modelnet40_ply_hdf5_2048.zip

**Comment by vinits5** [comment]
This is alternative path for the same dataset.
https://drive.google.com/drive/folders/17YHlezqGWkKMU2m_YU2hM2uWag_6OAu6?usp=sharing
