### ISSUE TITLE
pointnet2_cuda not in the repository?

### ISSUE THREAD

**Issue by anamtr94** [vinits5/learning3d#4]
Hi @vinits5. First of all, thanks a lot for sharing this library, it looks really interesting.

I am trying to compile the library and run the test_dcp.py script. However, the code complains and does not work because "pointnet2_cuda" cannot be imported. Is the file missing from the repository or is there something else?

Cheers!

**Comment by vinits5** [comment]
Hi @anamtr94, sorry for the delay in response.
You will have to compile the pointnet_2. In the utils/lib/ folder, there is a setup.py file. You can simply run that file to compile pointnet_2_cuda. Please let me know if you are still facing the errors. I will work on them. Thanks.
