### ISSUE TITLE
PCN Model: ClassificationData: Line 9:

### ISSUE THREAD

**Issue by rajprasad001** [vinits5/learning3d#5]
Hello @vinits5, Thanks for the repo. I am facing a challenge in a segment of your code.

I am not able to understand ClassificationData class. 'pcs' and 'labels' are passed in `find_attribute` method and later the shape is checked in `check_data` method. since the arguments are strings, I am getting confused with the purpose.

As per the invocation of Classification data is getting dataloader with 2 dimension shape(1024,3)
` self.pcs = self.find_attribute('pcs')`

Further, I am getting an error as mentioned below:-

```
assert 1 < len(self.pcs.shape) < 4, "Error in dimension of point clouds! Given data dimension: {}".format(
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by vinits5** [comment]
Hi @rajprasad001,
Sorry for the delay in response.
For the user's data, you need to provide a dictionary to the classification dataset with keys 'pcs' and 'labels'. Find attribute method will find the data associated with each key and will store it in self.pcs and self.labels. Later it will check the shape of these two variables. 
Ideally, your point cloud can be (batch_size, num_points, 3) or (num_points, 3). This function reshapes the input to the network according to the shape that is provided by user as pytorch requires a specific shape of input. 

I found the issue with the error. I have resolved it. Please feel free to pull it. Sorry for the inconvenience.
