### ISSUE TITLE
Is this library functional?

### ISSUE THREAD

**Issue by ysig** [vinits5/learning3d#7]
I am trying to use your library in a project, but I constantly get problems?
Is it functional?
Also you don't have github versions or releases so I can't pick an older functional part of it.

**Comment by ysig** [comment]
Also:
  File "/content/drive/MyDrive/learning3d/models/deepgmr.py", line 130
    self.backbone = feature_model if is not None else PointNet(use_rri=use_rri, nearest_neighbors=nearest_neighbors)

**Comment by ysig** [comment]
What I run is just:
```

from learning3d.models import Classifier, PointNet
from learning3d.losses import ClassificationLoss
from learning3d.data_utils import UserData
```

**Comment by vinits5** [comment]
Hello @ysig,
Really sorry for the delay in response. That typo is resolved. "is" should not be there. I have pushed the latest code.
I will soon create pip library versions of this repo for a smooth transition.
Thanks.
